# -*- coding: utf-8 -*-
"""HC Chap1.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuF-ZA8NuMQfMze5g8ochdfWV6H0ccBQ

### The Pipeline Function
"""

from transformers import pipeline

classifer = pipeline("sentiment-analysis")
classifer("I love the Spicy chicen tenders!")

"""### Zero-shot classification"""

classifer = pipeline("zero-shot-classification")
classifer(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

"""### Text Generation"""

generator = pipeline("text-generation")
generator("In this course, we will teach you how to")

"""### NER"""

ner = pipeline("ner", grouped_entities=True)
ner("My name is Sylvain and I work at Hugging Face in Brooklyn.")

"""### Question Answering"""

question_answerer = pipeline("question-answering")
question_answerer(
    question="Where do I work?",
    context="My name is Sylvain and I work at Hugging Face in Brooklyn",
)

"""### Summarization"""

summarizer = pipeline("summarization")
summarizer(
    """
    America has changed dramatically during recent years. Not only has the number of
    graduates in traditional engineering disciplines such as mechanical, civil,
    electrical, chemical, and aeronautical engineering declined, but in most of
    the premier American universities engineering curricula now concentrate on
    and encourage largely the study of engineering science. As a result, there
    are declining offerings in engineering subjects dealing with infrastructure,
    the environment, and related issues, and greater concentration on high
    technology subjects, largely supporting increasingly complex scientific
    developments. While the latter is important, it should not be at the expense
    of more traditional engineering.

    Rapidly developing economies such as China and India, as well as other
    industrial countries in Europe and Asia, continue to encourage and advance
    the teaching of engineering. Both China and India, respectively, graduate
    six and eight times as many traditional engineers as does the United States.
    Other industrial countries at minimum maintain their output, while America
    suffers an increasingly serious decline in the number of engineering graduates
    and a lack of well-educated engineers.
"""
)

"""### Translation"""

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en")
translator("Ce cours est produit par Hugging Face.")

"""### Image classification"""

image_classifier = pipeline(
    task="image-classification", model="google/vit-base-patch16-224"
)
result = image_classifier(
    "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/pipeline-cat-chonk.jpeg"
)
print(result)

"""### Automatic Speech Recognition"""

transcriber = pipeline(
    task="automatic-speech-recognition", model="openai/whisper-large-v3"
)
result = transcriber(
    "https://huggingface.co/datasets/Narsil/asr_dummy/resolve/main/mlk.flac"
)
print(result)