# -*- coding: utf-8 -*-
"""HC Chap1.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuF-ZA8NuMQfMze5g8ochdfWV6H0ccBQ

### The Pipeline Function
"""

from transformers import pipeline

classifer = pipeline("sentiment-analysis")
classifer("I love the Spicy chicen tenders!")

"""### Zero-shot classification"""

classifer = pipeline("zero-shot-classification")
classifer(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

"""### Text generation"""

generator = pipeline("text-generation")
generator("In this course, we will teach you how to")

generator = pipeline("text-generation", model="HuggingFaceTB/SmolLM2-360M")
generator(
    "In this course, we will teach you how to",
    max_length=30,
    num_return_sequences=2,
)

"""### Mask Filling"""

unmasker = pipeline("fill-mask")
unmasker("This course will teach you all about <mask> models.", top_k=2)



